### ISSUE TITLE
Project file missing

### ISSUE THREAD

**Issue by lizy14** [nero19960329/DIPSoftware#1]
`DIPSoftware\DIPSoftware.vcxproj`, referred to by `DIPSoftware.sln`, is missing from the repository.

error raised: `Object reference not set to an instance of an object.`

**Comment by nero19960329** [comment]
应该是我之前少上传了...等我回去拿笔记本上传下...thanks~

**Comment by nero19960329** [comment]
Oooooops....

**Comment by lizy14** [comment]
No worries, I was just going over open issues under my github account
